languageCode = "en"
languageName = "English"
weight = 1
title = "Haru's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006 January 2"

[params.author]
name = "Haru Zheng"
