[[main]]
name = "Home"
pageRef = "/"
identifier = "home"
weight = 1

[[main]]
name = "About"
pageRef = "about"
identifier = "about"
weight = 2

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "blog"
weight = 3

[[footer]]
name = "Contact"
pageRef = "contact"
identifier = "contact"
weight = 1
